/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayOfObjects: typeof import('./../src/components/array-of-objects/index.vue')['default']
    Csm: typeof import('./../src/components/csm/index.vue')['default']
    DatetimeLabel: typeof import('./../src/components/datetime-label/index.vue')['default']
    DatetimeSelector: typeof import('./../src/components/datetime-selector/index.vue')['default']
    EditButtons: typeof import('./../src/components/edit-buttons/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    EmptyInfo: typeof import('./../src/components/empty-info/index.vue')['default']
    FilterableListFrame: typeof import('./../src/components/filterable-list-frame/index.vue')['default']
    KeywordBox: typeof import('./../src/components/keyword-box/index.vue')['default']
    Paginator: typeof import('./../src/components/paginator/index.vue')['default']
    PlainText: typeof import('./../src/components/plain-text/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowPane: typeof import('./../src/components/shadow-pane/index.vue')['default']
    SimpleBarChart: typeof import('./../src/components/simple-bar-chart/index.vue')['default']
    SimpleLineChart: typeof import('./../src/components/simple-line-chart/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableColumnBoolean: typeof import('./../src/components/table-column-boolean/index.vue')['default']
    TableColumnClickable: typeof import('./../src/components/table-column-clickable/index.vue')['default']
    TableColumnDt: typeof import('./../src/components/table-column-dt/index.vue')['default']
    TableColumnSmv: typeof import('./../src/components/table-column-smv/index.vue')['default']
    TableColumnUser: typeof import('./../src/components/table-column-user/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
