server {
    # folder structure:
    # <live>
    # > /upload-------------------uploaded files(NEED BACKUP!)
    # > /.env---------------------environment configs for the backend(NEED BACKUP!)
    # > /static-------------------import/export excel files. These files are nearly temporary
    # > /frontend-----------------compiled frontend code
    # > /backend------------------folder only for backend docker container mounting

    listen 81;
    server_name cloud.eb-tech.cn

    # set buffer size
    proxy_buffer_size 64k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;

    location /upload {
        root /root/cmp;
    }

    location /static {
        root /root/cmp;
    }

    location /api {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/api/(.*) /$1 break;
        client_max_body_size 128m;
    }

    location / {
        root /root/cmp/frontend;
        try_files $uri $uri/ /index.html;
        index index.html;
        expires 1h;
    }
}