# Author: kk.Fang(fkfkbill@gmail.com)

# 时间格式(arrow)

COMMON_DATE_FORMAT = 'YYYY-MM-DD'
COMMON_DATE_FORMAT_COMPACT = 'YYYYMMDD'
COMMON_TIME_FORMAT = 'HH:mm:ss'
COMMON_TIME_FORMAT_COMPACT = 'HHmmss'
COMMON_DATETIME_FORMAT = f"{COMMON_DATE_FORMAT} {COMMON_TIME_FORMAT}"
COMMON_DATETIME_FORMAT_COMPACT = f"{COMMON_DATE_FORMAT_COMPACT}{COMMON_TIME_FORMAT_COMPACT}"
